TRUNCATE TABLE resultat RESTART IDENTITY cascade;
TRUNCATE TABLE match RESTART IDENTITY cascade;
TRUNCATE TABLE equipe_tournoi RESTART IDENTITY cascade;
TRUNCATE TABLE equipe RESTART IDENTITY cascade;
TRUNCATE TABLE type_match RESTART IDENTITY cascade;
TRUNCATE TABLE tournoi RESTART IDENTITY cascade;
TRUNCATE TABLE poule RESTART IDENTITY cascade;
TRUNCATE TABLE discipline RESTART IDENTITY cascade;
TRUNCATE TABLE utilisateur RESTART IDENTITY cascade;

